### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by kurtmc** [Alchemy-Agencies/alchemy-issues#10]
It would be good to also have a “terms of use” tick box for the first time they log on, where we can get their agreement to only download documents for their company’s use and not for further distribution (ie. Supplying info to our competitors)

Things

- Add "Accepted terms of use" boolean to customer users table
- Allow for updating this value through the api
- Add a a misc table to the site, and add a terms of use value, and a UI way to update it and a api way to retrieve it. (http://stackoverflow.com/questions/7679329/using-activerecord-with-key-value-pair-table)

**Comment by joshofreeness** [comment]
`curl -H 'Content-Type: application/json' -H 'Accept: application/json' -X GET -d '{"user":{"email":"api@user.com","password":"password"}}' http://localhost:3000/api/config_table`

Gets all the current key/value pairs from the api.
This can be an empty array if terms of use has not been initialised
