### ISSUE TITLE
Back up data

### ISSUE THREAD

**Issue by kurtmc** [Alchemy-Agencies/alchemy-issues#7]
Implement back up schedules for the internal and external websites.

**Comment by kurtmc** [comment]
This will be useful for the documents storage. https://github.com/bobbo/git-s3-push

**Comment by joshofreeness** [comment]
Also maybe this https://gist.github.com/oodavid/2206527

(dockerised) https://github.com/schickling/dockerfiles/tree/master/mysql-backup-s3
