### ISSUE TITLE
Welcome on external website

### ISSUE THREAD

**Issue by kurtmc** [Alchemy-Agencies/alchemy-issues#8]
Can we personalise the greeting – rather than ‘You are currently logged in as ….” Could we have Welcome ‘Cheryl” from “Nutrimetics” to the secure login section of Alchemy Agency’s website [LOG OUT]
If you experience any technical difficulties please email with details to admin@alchemyagencies.co.nz

TODO:

- Create migration that adds customer name and customer company name fields to the 'CustomerUsers' table
- Make sure this is exposed through the JSON api
- Make changes to the php website to show this new information.

**Comment by joshofreeness** [comment]
@kurtmc  Does this also need changes to the controllers of the internal-website for show/edit/new etc?

**Comment by kurtmc** [comment]
@joshofreeness there should be minimal changes to the controller.

Most of the changes will be in the database, model and views.

**Comment by kurtmc** [comment]
:shipit:
